### ISSUE TITLE
index for rest

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/book#11]
create meaningful latex index for rest. if you do not know how, see other sections for example

**Comment by vibhatha** [comment]
It is not clear to me ? What do you mean by index ?
Title ???

**Comment by laszewsk** [comment]
\index{Rest!Eve}
\index{Eve}

read up on in latex doc

**Comment by vibhatha** [comment]
Got it.

**Comment by vibhatha** [comment]
Indexes were added
