### ISSUE TITLE
Docker REST

### ISSUE THREAD

**Issue by tbalson** [cloudmesh/book#150]
* [x]  Slides:
* [x]  Handbook: https://github.com/cloudmesh/book/blob/master/section/container/docker-rest.md
* [x]  Integrated into handbook:

**Comment by vibhatha** [comment]
There are no specific slides created for this section, this is a section of the handbook. Docker was discussed as a lecture and it is in

https://github.com/cloudmesh/book/blob/master/section/container/container.tex

The docker rest material can be found here and it is already in the handbook. 

https://github.com/cloudmesh/book/blob/master/section/container/docker-rest.tex
