### ISSUE TITLE
MapReduce

### ISSUE THREAD

**Issue by tbalson** [cloudmesh/book#156]
* [x] Slides: 
   * [x] Handbook:
   * [x] Integrated into handbook:

**Comment by vibhatha** [comment]
MapReduce contains Spark, Hadoop and Twister2 sections. 

https://github.com/cloudmesh/book/blob/master/section/mapreduce/spark-lectures.tex
https://github.com/cloudmesh/book/blob/master/section/mapreduce/hadoop-lectures.tex
https://github.com/cloudmesh/book/blob/master/section/mapreduce/hadoop-installation.tex
https://github.com/cloudmesh/book/blob/master/section/mapreduce/twister-installation.tex
https://github.com/cloudmesh/book/blob/master/section/mapreduce/spark-streaming.tex

These are the links containing slides and material bound to the book. These are already in the book.
