### ISSUE TITLE
Virtual Machines

### ISSUE THREAD

**Issue by tbalson** [cloudmesh/book#158]
* [ ] Slides: https://1drv.ms/p/s!AvpSEd2J24STjBbo4k35C5v-ra8g
   * [ ] Handbook:
   * [ ] Integrated into handbook:

**Comment by bfeng** [comment]
* [ ] Slides: https://1drv.ms/p/s!AvpSEd2J24STjBbo4k35C5v-ra8g
   * [ ] Handbook: https://github.com/cloudmesh/book/tree/master/section/virtualmachines
   * [ ] Integrated into handbook: Yes
