### ISSUE TITLE
bio check

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/book#18]
check for all classes if 

* [x] bio was posted
* [x] bio was included in google docs

get in contact with students that did not do that via private piaza post. in some cases if we know they have not posted to piazza we need to also send via canvas to make sure they know what we do

**Comment by tbalson** [comment]
e222

Everyone minus Max posted to piazza. 

google doc for e222? Is there one? 

Max has not posted and a message was sent (1/29/17 through canvas 

516 Everyone has posted to piazza. 

Naveen Kaul (Canvas has him registered in i524/piazza is 516) hid is assigned for i524.

516 google doc missing Arnav, Arnav 
Arra, Goutham, Athaley, Sushant, Axthelm, Alexander and Leite, John have pasted their bios into the document however they haven't listed the subsection in the beginning of the document. 

616/524

Everyone has posted to Piazza

All but Swaroop, Saurabh has pasted bio into google doc, Kugan, Uma didn't include /subsection at the stat of the page but the bio is in the document.

**Comment by tbalson** [comment]
bios were graded

**Comment by laszewsk** [comment]
issued
