### ISSUE TITLE
create git repos based on hid

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/book#25]
we should look at the script thing posted in the plan doc.
need to do this monday

**Comment by laszewsk** [comment]
https://github.com/bertvv/github-org-mgmt

**Comment by laszewsk** [comment]
some people have not yet responded to survey, but we should just get started on creation of the once we have

**Comment by laszewsk** [comment]
Not yet sure if we need miao

* [ ] gregor gets survey results
* [ ] tyler puts data in spreadsheet
* [ ] tyler creates spredsheet with hid and github name only
* [ ] gregor creates accounts on iuclasses repo

* [ ] cleanup of iuclasses repo as we use book and not iu classes

**Comment by tbalson** [comment]
Done
