### ISSUE TITLE
REST code snippet addition

### ISSUE THREAD

**Issue by vibhatha** [cloudmesh/book#57]

**Comment by vibhatha** [comment]
The codes were added

https://github.com/cloudmesh/book/blob/dev/section/rest/rest-code.md

**Comment by laszewsk** [comment]
so is it added to the handbook and student can find it?

**Comment by laszewsk** [comment]
so you need to add this to rest.tex also and have a section about this.

**Comment by vibhatha** [comment]
Actullly this what you asked me to create a md file to help them get codes
easily.

With Regards,
Vibhatha Abeykoon

**Comment by vibhatha** [comment]
I will add the url.

**Comment by vibhatha** [comment]
Url was added to rest.tex
