### ISSUE TITLE
lecture minikube

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/book#61]
* md link?
* slides link ?

**Comment by bfeng** [comment]
MD link: https://drive.google.com/file/d/1TQALwC4SMAkd1JncnT3EbzJJ0ok_3Vx-/view?usp=sharing
Slides link: https://onedrive.live.com/view.aspx?cid=a2320ac02dfde030&page=view&resid=9384DB89DD1152FA!1524&parId=9384DB89DD1152FA!1507&app=PowerPoint
