### ISSUE TITLE
MapReduce Lectures

### ISSUE THREAD

**Issue by vibhatha** [cloudmesh/book#62]
Link to Sildes [https://docs.google.com/presentation/d/1n2LxtdMD28KnIN3wVKIckNDaZ_lTIYXBTIOX69EIpCc/edit?usp=sharing](url)
- [ ] Basic theory 
  - [X] Map reduce theory 
  - [x] Hadoop
  - [x] Spark
  - [ ] Wordcount
  - [ ] Intro to Labs

- [x] Lab Design
  - [x] Md on Installation of Hadoop 
  - [x] Add to book
  - [x] Prepare md file

**Comment by vibhatha** [comment]
I have added the hadoop-installation file to the book and updated the earlier tutorial with proper ssh configuration with password and a sudo user. 

https://github.com/cloudmesh/book/blob/master/section/hadoop/hadoop-installation.tex

**Comment by laszewsk** [comment]
is this integrated in some fashion into a hadoop part/cahpter that is already visible in the handbook?

**Comment by vibhatha** [comment]
this is in 
section/hadoop/hadoop-installation.tex

**Comment by vibhatha** [comment]
I added a section to von-laszewsk.tex using include tag. 
Just committed that as well.
