### ISSUE TITLE
URGENT: cloud section

### ISSUE THREAD

**Issue by laszewsk** [cloudmesh/book#67]
https://github.com/cloudmesh/book/blob/dev/part/icloud.tex

* [x] fix page length in the right position
* [x] introduce the subsections
* [x] add the where commands to the syllabus of 516 to all sections
* [x] add the where commands to the syllabus of 616 to all sections
* [x] post release of lectures to piazza 516
* [x] post release of lectures to piazza 616

**Comment by vibhatha** [comment]
@laszewsk 
Fix page length in right position means the slide number in the right place in fundamentals.tex file ?
Am I right ?

Could you please give a brief description on each job. Tyler and I discussed, it is a bit unclear to us. As soon as it is clear we can finish it within an hour.

**Comment by vibhatha** [comment]
Pages were updated accordingly 6 days ago.

**Comment by vibhatha** [comment]
@tbalson 

are we done with the unticked tasks ?
I am not sure. Could you please check.

**Comment by vibhatha** [comment]
Tyler and I completed the task.
