### ISSUE TITLE
MapReduce 2: Spark Installation on Docker 

### ISSUE THREAD

**Issue by vibhatha** [cloudmesh/book#80]
MapReduce Part 2 Lecture : Interactive lecture with Labs.  
  - [ ] Hadoop Wordcount 
  - [ ] Spark Installation
  - [ ] Spark Wordcount

**Comment by vibhatha** [comment]
@bfeng  how is the spark tutorial ?

**Comment by bfeng** [comment]
Spark on Docker can be found here: https://github.com/cloudmesh/book/blob/master/section/container/docker-spark.tex
