### ISSUE TITLE
Lab : 22/02/2018 : Flask Docker REST API

### ISSUE THREAD

**Issue by vibhatha** [cloudmesh/book#84]

**Comment by vibhatha** [comment]
Completed the lab 

[Labs MD](https://github.com/cloudmesh/book/blob/master/section/container/docker-rest.md)

Please test it on Ubuntu and Mac OS. 

Working on windows section. 

@bfeng  test on Mac
@lee212  test on Ubuntu 16.04

**Comment by laszewsk** [comment]
can you please convert via pandoc to tex, cleanup, include in the handbook and delete the md file so we a single source by tomorrow.

**Comment by vibhatha** [comment]
Tested by Professor Fox and me on windows.
